### ISSUE TITLE
[epic] Need to interact with GPT after all steps are "DONE"

### ISSUE THREAD

**Issue by nalbion** [Pythagora-io/gpt-pilot#68]
When re-running gpt-pilot on a project with all steps "DONE" I'm prompted with:

 > How did GPT Pilot do? Were you able to create any app that works? Please write any feedback you have or just press ENTER to exit:
 
 I would prefer to be able to interact further with the AI:

- [ ] Dump the final summary to {workspace}/.gpt-pilot.yml or .md.  #238 
- [ ] Edit the final summary directly or by conversation
- [ ] #91 Choose to speak with Architect/ProductOwner/TechLead
- [ ] Change, remove or add extra requirements/stories - see #83
- [ ] Ask questions about the code - failing tests, integration issues between front/back-ends.
- [ ] #83 List open issues from Jira/Github etc & work on them

**Comment by nalbion** [comment]
```[tasklist]
### Tasks
- [ ] Dump the final summary to {workspace}/.gpt-pilot.yml or .md.
- [ ] Edit the final summary directly or by conversation
- [ ] Choose to speak with Architect/ProductOwner/TechLead to change, remove or add extra requirements/stories.
- [ ] Ask questions about the code - failing tests, integration issues between front/back-ends.
- [ ] #83 List open issues from Jira/Github etc & work on them
```
